### ISSUE TITLE
Sanıyorum imajlar bozulmuş

### ISSUE THREAD

**Issue by miratcan** [maidis/math-as-code#1]

**Comment by maidis** [comment]
Bu hafta sonundaki AÖF sınavlarına çalışmamak için bahane arayıp duruyor ve çok da zorlanmıyordum açıkçası :) Sağ ol bugünlük bir bahanem daha olmuş oldu :)

**Comment by maidis** [comment]
Teşekkürler, düzelmiş olmalı.

https://github.com/maidis/kod-olarak-matematik-cpp/commit/9fa48ba20f9a3aeb88a7da78a715af80d95fdc72
